package EDOM.editor;

/*Generated by MPS */

import jetbrains.mps.lang.editor.forms.runtime.AbstractToggleCheckboxAction;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.nodeEditor.selectionRestoring.CellSelector;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.selectionRestoring.WholeCellSelector;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ToggleCheckboxAction_gt4ssm_b3a extends AbstractToggleCheckboxAction {
  private final SNode myNode;

  public ToggleCheckboxAction_gt4ssm_b3a(SNode node) {
    myNode = node;
  }

  protected void doExecute() {
    SPropertyOperations.assign(myNode, PROPS.hasReply$Tgsu, !(SPropertyOperations.getBoolean(myNode, PROPS.hasReply$Tgsu)));
  }

  protected CellSelector createCellSelector(EditorCell selectedCell) {
    return new WholeCellSelector();
  }

  private static final class PROPS {
    /*package*/ static final SProperty hasReply$Tgsu = MetaAdapterFactory.getProperty(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x4dd8eed996c07227L, 0x4dd8eed996c07228L, "hasReply");
  }
}
