//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isep.edom.gorgeous
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "gorgeous";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"gorgeous";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"CR2";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID gorgeousDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(gorgeousCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID gorgeousExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(gorgeousCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewgorgeousExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(gorgeousCommandSetId), 0x0001);
	
		// Package identifier
		public const string gorgeousPackageId = "37a54dce-c7ce-43f1-b9ea-0718eb16847c";
		
		// Editor factory identifier
		public const string gorgeousEditorFactoryId = "c9f4a045-4b5f-4bd2-9e88-481434b102a1";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string gorgeousModelExplorerToolWindowId = "3ff2ac96-a7cb-45bd-ae87-7e5fe137b47e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace isep.edom.gorgeous
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string gorgeousCommandSetId = "53f7e8ca-5cb9-4ce9-8b6b-00f38d35de56";
	}
}