//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace isep.edom.gorgeous
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(gorgeousExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(gorgeousExplorerToolWindow), Constants.gorgeousEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@gorgeousToolboxTab;isep.edom.gorgeous.Dsl.dll", "isep.edom.gorgeous.gorgeousToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@UserToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.UserToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"User", 
					"@UserToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@SubjectToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.SubjectToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Subject", 
					"@SubjectToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@ReviewToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.ReviewToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Review", 
					"@ReviewToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@CommentToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.CommentToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Comment", 
					"@CommentToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@FieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.FieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Field", 
					"@FieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@AbsRevComToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.AbsRevComToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AbsRevCom", 
					"@AbsRevComToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@SubjectHasFieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.SubjectHasFieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SubjectHasField", 
					"@SubjectHasFieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@SubjectHasReviewCommentToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.SubjectHasReviewCommentToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SubjectHasReviewComment", 
					"@SubjectHasReviewCommentToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@UserHasFieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.UserHasFieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"UserHasField", 
					"@UserHasFieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@ReviewExtendRevComToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.ReviewExtendRevComToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ReviewExtendRevCom", 
					"@ReviewExtendRevComToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@ReviewByUserToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.ReviewByUserToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ReviewByUser", 
					"@ReviewByUserToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@ReviewHasFieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.ReviewHasFieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ReviewHasField", 
					"@ReviewHasFieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@CommentByUserToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.CommentByUserToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommentByUser", 
					"@CommentByUserToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@CommentHasFieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.CommentHasFieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommentHasField", 
					"@CommentHasFieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@CommentHasCommentToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.CommentHasCommentToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommentHasComment", 
					"@CommentHasCommentToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@CommentExtendRevComToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.CommentExtendRevComToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CommentExtendRevCom", 
					"@CommentExtendRevComToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("isep.edom.gorgeous.gorgeousToolboxTab",
					"@RevComHasFieldToolboxItem;isep.edom.gorgeous.Dsl.dll", 
					"isep.edom.gorgeous.RevComHasFieldToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RevComHasField", 
					"@RevComHasFieldToolboxBitmap;isep.edom.gorgeous.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideEditorFactory(typeof(gorgeousEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(gorgeousEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(gorgeousEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"gorgeous", typeof(gorgeousEditorFactory))]

	internal abstract partial class gorgeousPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::isep.edom.gorgeous.gorgeousToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new gorgeousEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::isep.edom.gorgeous.gorgeousToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			gorgeousCommandSet commandSet = new gorgeousCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			gorgeousClipboardCommandSet clipboardCommandSet = new gorgeousClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(gorgeousExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(gorgeousExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace isep.edom.gorgeous
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::isep.edom.gorgeous.gorgeousDirectiveProcessor), global::isep.edom.gorgeous.gorgeousDirectiveProcessor.gorgeousDirectiveProcessorName, "A directive processor that provides access to gorgeous files")]
	[global::System.Runtime.InteropServices.Guid(Constants.gorgeousPackageId)]
	internal sealed partial class gorgeousPackage : gorgeousPackageBase
	{
	}
}