//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace isep.edom.gorgeous
{
	/// <summary>
	/// DomainModel gorgeousDomainModel
	/// Description for isep.edom.gorgeous.gorgeous
	/// </summary>
	[DslDesign::DisplayNameResource("isep.edom.gorgeous.gorgeousDomainModel.DisplayName", typeof(global::isep.edom.gorgeous.gorgeousDomainModel), "isep.edom.gorgeous.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("isep.edom.gorgeous.gorgeousDomainModel.Description", typeof(global::isep.edom.gorgeous.gorgeousDomainModel), "isep.edom.gorgeous.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("08246ac6-6952-4568-aa24-1f3597385041")]
	public partial class gorgeousDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// gorgeousDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x08246ac6, 0x6952, 0x4568, 0xaa, 0x24, 0x1f, 0x35, 0x97, 0x38, 0x50, 0x41);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public gorgeousDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Model),
				typeof(User),
				typeof(Subject),
				typeof(Review),
				typeof(Comment),
				typeof(Field),
				typeof(ReviewComment),
				typeof(Process),
				typeof(Node),
				typeof(Automatic),
				typeof(Manual),
				typeof(ModelTemUser),
				typeof(ModelTemSubject),
				typeof(ModelTemReview),
				typeof(ModelTemComment),
				typeof(ModelTemField),
				typeof(SubjectReferênciasUser),
				typeof(ReviewReferênciasUser),
				typeof(CommentReferênciasUser),
				typeof(CommentReferênciasField),
				typeof(ReviewReferênciasField),
				typeof(SubjectReferênciasField),
				typeof(UserReferênciasField),
				typeof(CommentReferênciasDestinoComment),
				typeof(ModelTemReviewComment),
				typeof(ReviewCommentReferênciasField),
				typeof(SubjectReferênciasReviewComment),
				typeof(ReviewReferênciasReviewComment),
				typeof(CommentReferênciasReviewComment),
				typeof(ModelTemProcess),
				typeof(CommentReferênciasProcess),
				typeof(ModelTemNode),
				typeof(ProcessReferênciasNode),
				typeof(NodeReferênciasField),
				typeof(ModelTemAutomatic),
				typeof(ModelTemManual),
				typeof(AutomaticReferênciasNode),
				typeof(ManualReferênciasNode),
				typeof(gorgeousDiagram),
				typeof(HasConnector),
				typeof(ByConnector),
				typeof(ExtendConnector),
				typeof(UserShape),
				typeof(SubjectShape),
				typeof(ReviewShape),
				typeof(CommentShape),
				typeof(FieldShape),
				typeof(RevComShape),
				typeof(ProcessShape),
				typeof(NodeShape),
				typeof(AuMaShape),
				typeof(global::isep.edom.gorgeous.FixUpDiagram),
				typeof(global::isep.edom.gorgeous.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Model), "Name", Model.NameDomainPropertyId, typeof(Model.NamePropertyHandler)),
				new DomainMemberInfo(typeof(User), "Name", User.NameDomainPropertyId, typeof(User.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Subject), "Name", Subject.NameDomainPropertyId, typeof(Subject.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Review), "Name", Review.NameDomainPropertyId, typeof(Review.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Comment), "Name", Comment.NameDomainPropertyId, typeof(Comment.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Field), "Name", Field.NameDomainPropertyId, typeof(Field.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Field), "Type", Field.TypeDomainPropertyId, typeof(Field.TypePropertyHandler)),
				new DomainMemberInfo(typeof(ReviewComment), "Name", ReviewComment.NameDomainPropertyId, typeof(ReviewComment.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Process), "Name", Process.NameDomainPropertyId, typeof(Process.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Node), "Name", Node.NameDomainPropertyId, typeof(Node.NamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(ModelTemUser), "Model", ModelTemUser.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemUser), "User", ModelTemUser.UserDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemSubject), "Model", ModelTemSubject.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemSubject), "Subject", ModelTemSubject.SubjectDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemReview), "Model", ModelTemReview.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemReview), "Review", ModelTemReview.ReviewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemComment), "Model", ModelTemComment.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemComment), "Comment", ModelTemComment.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemField), "Model", ModelTemField.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemField), "Field", ModelTemField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasUser), "Subject", SubjectReferênciasUser.SubjectDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasUser), "User", SubjectReferênciasUser.UserDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasUser), "Review", ReviewReferênciasUser.ReviewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasUser), "User", ReviewReferênciasUser.UserDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasUser), "Comment", CommentReferênciasUser.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasUser), "User", CommentReferênciasUser.UserDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasField), "Comment", CommentReferênciasField.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasField), "Field", CommentReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasField), "Review", ReviewReferênciasField.ReviewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasField), "Field", ReviewReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasField), "Subject", SubjectReferênciasField.SubjectDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasField), "Field", SubjectReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(UserReferênciasField), "User", UserReferênciasField.UserDomainRoleId),
				new DomainRolePlayerInfo(typeof(UserReferênciasField), "Field", UserReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasDestinoComment), "OrigemComment", CommentReferênciasDestinoComment.OrigemCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasDestinoComment), "DestinoComment", CommentReferênciasDestinoComment.DestinoCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemReviewComment), "Model", ModelTemReviewComment.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemReviewComment), "ReviewComment", ModelTemReviewComment.ReviewCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewCommentReferênciasField), "ReviewComment", ReviewCommentReferênciasField.ReviewCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewCommentReferênciasField), "Field", ReviewCommentReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasReviewComment), "Subject", SubjectReferênciasReviewComment.SubjectDomainRoleId),
				new DomainRolePlayerInfo(typeof(SubjectReferênciasReviewComment), "ReviewComment", SubjectReferênciasReviewComment.ReviewCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasReviewComment), "Review", ReviewReferênciasReviewComment.ReviewDomainRoleId),
				new DomainRolePlayerInfo(typeof(ReviewReferênciasReviewComment), "ReviewComment", ReviewReferênciasReviewComment.ReviewCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasReviewComment), "Comment", CommentReferênciasReviewComment.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasReviewComment), "ReviewComment", CommentReferênciasReviewComment.ReviewCommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemProcess), "Model", ModelTemProcess.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemProcess), "Process", ModelTemProcess.ProcessDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasProcess), "Comment", CommentReferênciasProcess.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferênciasProcess), "Process", CommentReferênciasProcess.ProcessDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemNode), "Model", ModelTemNode.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemNode), "Node", ModelTemNode.NodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(ProcessReferênciasNode), "Process", ProcessReferênciasNode.ProcessDomainRoleId),
				new DomainRolePlayerInfo(typeof(ProcessReferênciasNode), "Node", ProcessReferênciasNode.NodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(NodeReferênciasField), "Node", NodeReferênciasField.NodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(NodeReferênciasField), "Field", NodeReferênciasField.FieldDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemAutomatic), "Model", ModelTemAutomatic.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemAutomatic), "Automatic", ModelTemAutomatic.AutomaticDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemManual), "Model", ModelTemManual.ModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelTemManual), "Manual", ModelTemManual.ManualDomainRoleId),
				new DomainRolePlayerInfo(typeof(AutomaticReferênciasNode), "Automatic", AutomaticReferênciasNode.AutomaticDomainRoleId),
				new DomainRolePlayerInfo(typeof(AutomaticReferênciasNode), "Node", AutomaticReferênciasNode.NodeDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManualReferênciasNode), "Manual", ManualReferênciasNode.ManualDomainRoleId),
				new DomainRolePlayerInfo(typeof(ManualReferênciasNode), "Node", ManualReferênciasNode.NodeDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(24);
				createElementMap.Add(typeof(Model), 0);
				createElementMap.Add(typeof(User), 1);
				createElementMap.Add(typeof(Subject), 2);
				createElementMap.Add(typeof(Review), 3);
				createElementMap.Add(typeof(Comment), 4);
				createElementMap.Add(typeof(Field), 5);
				createElementMap.Add(typeof(ReviewComment), 6);
				createElementMap.Add(typeof(Process), 7);
				createElementMap.Add(typeof(Node), 8);
				createElementMap.Add(typeof(Automatic), 9);
				createElementMap.Add(typeof(Manual), 10);
				createElementMap.Add(typeof(gorgeousDiagram), 11);
				createElementMap.Add(typeof(HasConnector), 12);
				createElementMap.Add(typeof(ByConnector), 13);
				createElementMap.Add(typeof(ExtendConnector), 14);
				createElementMap.Add(typeof(UserShape), 15);
				createElementMap.Add(typeof(SubjectShape), 16);
				createElementMap.Add(typeof(ReviewShape), 17);
				createElementMap.Add(typeof(CommentShape), 18);
				createElementMap.Add(typeof(FieldShape), 19);
				createElementMap.Add(typeof(RevComShape), 20);
				createElementMap.Add(typeof(ProcessShape), 21);
				createElementMap.Add(typeof(NodeShape), 22);
				createElementMap.Add(typeof(AuMaShape), 23);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::isep.edom.gorgeous.gorgeousDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Model(partition, propertyAssignments);
				case 1: return new User(partition, propertyAssignments);
				case 2: return new Subject(partition, propertyAssignments);
				case 3: return new Review(partition, propertyAssignments);
				case 4: return new Comment(partition, propertyAssignments);
				case 5: return new Field(partition, propertyAssignments);
				case 6: return new ReviewComment(partition, propertyAssignments);
				case 7: return new Process(partition, propertyAssignments);
				case 8: return new Node(partition, propertyAssignments);
				case 9: return new Automatic(partition, propertyAssignments);
				case 10: return new Manual(partition, propertyAssignments);
				case 11: return new gorgeousDiagram(partition, propertyAssignments);
				case 12: return new HasConnector(partition, propertyAssignments);
				case 13: return new ByConnector(partition, propertyAssignments);
				case 14: return new ExtendConnector(partition, propertyAssignments);
				case 15: return new UserShape(partition, propertyAssignments);
				case 16: return new SubjectShape(partition, propertyAssignments);
				case 17: return new ReviewShape(partition, propertyAssignments);
				case 18: return new CommentShape(partition, propertyAssignments);
				case 19: return new FieldShape(partition, propertyAssignments);
				case 20: return new RevComShape(partition, propertyAssignments);
				case 21: return new ProcessShape(partition, propertyAssignments);
				case 22: return new NodeShape(partition, propertyAssignments);
				case 23: return new AuMaShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(27);
				createElementLinkMap.Add(typeof(ModelTemUser), 0);
				createElementLinkMap.Add(typeof(ModelTemSubject), 1);
				createElementLinkMap.Add(typeof(ModelTemReview), 2);
				createElementLinkMap.Add(typeof(ModelTemComment), 3);
				createElementLinkMap.Add(typeof(ModelTemField), 4);
				createElementLinkMap.Add(typeof(SubjectReferênciasUser), 5);
				createElementLinkMap.Add(typeof(ReviewReferênciasUser), 6);
				createElementLinkMap.Add(typeof(CommentReferênciasUser), 7);
				createElementLinkMap.Add(typeof(CommentReferênciasField), 8);
				createElementLinkMap.Add(typeof(ReviewReferênciasField), 9);
				createElementLinkMap.Add(typeof(SubjectReferênciasField), 10);
				createElementLinkMap.Add(typeof(UserReferênciasField), 11);
				createElementLinkMap.Add(typeof(CommentReferênciasDestinoComment), 12);
				createElementLinkMap.Add(typeof(ModelTemReviewComment), 13);
				createElementLinkMap.Add(typeof(ReviewCommentReferênciasField), 14);
				createElementLinkMap.Add(typeof(SubjectReferênciasReviewComment), 15);
				createElementLinkMap.Add(typeof(ReviewReferênciasReviewComment), 16);
				createElementLinkMap.Add(typeof(CommentReferênciasReviewComment), 17);
				createElementLinkMap.Add(typeof(ModelTemProcess), 18);
				createElementLinkMap.Add(typeof(CommentReferênciasProcess), 19);
				createElementLinkMap.Add(typeof(ModelTemNode), 20);
				createElementLinkMap.Add(typeof(ProcessReferênciasNode), 21);
				createElementLinkMap.Add(typeof(NodeReferênciasField), 22);
				createElementLinkMap.Add(typeof(ModelTemAutomatic), 23);
				createElementLinkMap.Add(typeof(ModelTemManual), 24);
				createElementLinkMap.Add(typeof(AutomaticReferênciasNode), 25);
				createElementLinkMap.Add(typeof(ManualReferênciasNode), 26);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::isep.edom.gorgeous.gorgeousDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new ModelTemUser(partition, roleAssignments, propertyAssignments);
				case 1: return new ModelTemSubject(partition, roleAssignments, propertyAssignments);
				case 2: return new ModelTemReview(partition, roleAssignments, propertyAssignments);
				case 3: return new ModelTemComment(partition, roleAssignments, propertyAssignments);
				case 4: return new ModelTemField(partition, roleAssignments, propertyAssignments);
				case 5: return new SubjectReferênciasUser(partition, roleAssignments, propertyAssignments);
				case 6: return new ReviewReferênciasUser(partition, roleAssignments, propertyAssignments);
				case 7: return new CommentReferênciasUser(partition, roleAssignments, propertyAssignments);
				case 8: return new CommentReferênciasField(partition, roleAssignments, propertyAssignments);
				case 9: return new ReviewReferênciasField(partition, roleAssignments, propertyAssignments);
				case 10: return new SubjectReferênciasField(partition, roleAssignments, propertyAssignments);
				case 11: return new UserReferênciasField(partition, roleAssignments, propertyAssignments);
				case 12: return new CommentReferênciasDestinoComment(partition, roleAssignments, propertyAssignments);
				case 13: return new ModelTemReviewComment(partition, roleAssignments, propertyAssignments);
				case 14: return new ReviewCommentReferênciasField(partition, roleAssignments, propertyAssignments);
				case 15: return new SubjectReferênciasReviewComment(partition, roleAssignments, propertyAssignments);
				case 16: return new ReviewReferênciasReviewComment(partition, roleAssignments, propertyAssignments);
				case 17: return new CommentReferênciasReviewComment(partition, roleAssignments, propertyAssignments);
				case 18: return new ModelTemProcess(partition, roleAssignments, propertyAssignments);
				case 19: return new CommentReferênciasProcess(partition, roleAssignments, propertyAssignments);
				case 20: return new ModelTemNode(partition, roleAssignments, propertyAssignments);
				case 21: return new ProcessReferênciasNode(partition, roleAssignments, propertyAssignments);
				case 22: return new NodeReferênciasField(partition, roleAssignments, propertyAssignments);
				case 23: return new ModelTemAutomatic(partition, roleAssignments, propertyAssignments);
				case 24: return new ModelTemManual(partition, roleAssignments, propertyAssignments);
				case 25: return new AutomaticReferênciasNode(partition, roleAssignments, propertyAssignments);
				case 26: return new ManualReferênciasNode(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "isep.edom.gorgeous.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return gorgeousDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (gorgeousDomainModel.resourceManager == null)
				{
					gorgeousDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(gorgeousDomainModel).Assembly);
				}
				return gorgeousDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return gorgeousDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return gorgeousDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (gorgeousDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new gorgeousCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					gorgeousDomainModel.copyClosure = copyFilter;
				}
				return gorgeousDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (gorgeousDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new gorgeousDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					gorgeousDomainModel.removeClosure = removeFilter;
				}
				return gorgeousDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::isep.edom.gorgeous.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::isep.edom.gorgeous.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::isep.edom.gorgeous.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::isep.edom.gorgeous.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class gorgeousDeleteClosure : gorgeousDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public gorgeousDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class gorgeousDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public gorgeousDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemUser.UserDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemSubject.SubjectDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemReview.ReviewDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemComment.CommentDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemField.FieldDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemReviewComment.ReviewCommentDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemProcess.ProcessDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemNode.NodeDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemAutomatic.AutomaticDomainRoleId, true);
			DomainRoles.Add(global::isep.edom.gorgeous.ModelTemManual.ManualDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class gorgeousCopyClosure : gorgeousCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public gorgeousCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class gorgeousCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public gorgeousCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

