//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace isep.edom.gorgeous
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class gorgeousToolboxHelper : gorgeousToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new gorgeousToolboxHelper.
		/// </summary>
		public gorgeousToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class gorgeousToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify gorgeous toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "gorgeous.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify SubjectHasField connector tool.
		/// </summary>
		public const string SubjectHasFieldFilterString = "SubjectHasField.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify SubjectHasReviewComment connector tool.
		/// </summary>
		public const string SubjectHasReviewCommentFilterString = "SubjectHasReviewComment.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify UserHasField connector tool.
		/// </summary>
		public const string UserHasFieldFilterString = "UserHasField.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ReviewExtendRevCom connector tool.
		/// </summary>
		public const string ReviewExtendRevComFilterString = "ReviewExtendRevCom.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ReviewByUser connector tool.
		/// </summary>
		public const string ReviewByUserFilterString = "ReviewByUser.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ReviewHasField connector tool.
		/// </summary>
		public const string ReviewHasFieldFilterString = "ReviewHasField.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify CommentByUser connector tool.
		/// </summary>
		public const string CommentByUserFilterString = "CommentByUser.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify CommentHasField connector tool.
		/// </summary>
		public const string CommentHasFieldFilterString = "CommentHasField.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify CommentHasComment connector tool.
		/// </summary>
		public const string CommentHasCommentFilterString = "CommentHasComment.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify CommentExtendRevCom connector tool.
		/// </summary>
		public const string CommentExtendRevComFilterString = "CommentExtendRevCom.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RevComHasField connector tool.
		/// </summary>
		public const string RevComHasFieldFilterString = "RevComHasField.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new gorgeousToolboxHelperBase.
		/// </summary>
		protected gorgeousToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::isep.edom.gorgeous.gorgeousDomainModel.SingletonResourceManager.GetString("gorgeousToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 17;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::isep.edom.gorgeous.gorgeousDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "isep.edom.gorgeous.UserToolboxItem":
					// Add User shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.UserToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("UserToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("UserToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"User", // F1 help keyword for the toolbox item.
						resourceManager.GetString("UserToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.User.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.SubjectToolboxItem":
					// Add Subject shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.SubjectToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SubjectToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SubjectToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Subject", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SubjectToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.Subject.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.ReviewToolboxItem":
					// Add Review shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.ReviewToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ReviewToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ReviewToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Review", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ReviewToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.Review.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.CommentToolboxItem":
					// Add Comment shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.CommentToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CommentToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CommentToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Comment", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CommentToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.Comment.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.FieldToolboxItem":
					// Add Field shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.FieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Field", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.Field.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.AbsRevComToolboxItem":
					// Add AbsRevCom shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.AbsRevComToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AbsRevComToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AbsRevComToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AbsRevCom", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AbsRevComToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::isep.edom.gorgeous.ReviewComment.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "isep.edom.gorgeous.SubjectHasFieldToolboxItem":

					// Add SubjectHasField connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.SubjectHasFieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SubjectHasFieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SubjectHasFieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SubjectHasField", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SubjectHasFieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(SubjectHasFieldFilterString)
						});
					break;
				case "isep.edom.gorgeous.SubjectHasReviewCommentToolboxItem":

					// Add SubjectHasReviewComment connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.SubjectHasReviewCommentToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SubjectHasReviewCommentToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SubjectHasReviewCommentToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SubjectHasReviewComment", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SubjectHasReviewCommentToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(SubjectHasReviewCommentFilterString)
						});
					break;
				case "isep.edom.gorgeous.UserHasFieldToolboxItem":

					// Add UserHasField connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.UserHasFieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("UserHasFieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("UserHasFieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"UserHasField", // F1 help keyword for the toolbox item.
						resourceManager.GetString("UserHasFieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(UserHasFieldFilterString)
						});
					break;
				case "isep.edom.gorgeous.ReviewExtendRevComToolboxItem":

					// Add ReviewExtendRevCom connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.ReviewExtendRevComToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ReviewExtendRevComToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ReviewExtendRevComToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ReviewExtendRevCom", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ReviewExtendRevComToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ReviewExtendRevComFilterString)
						});
					break;
				case "isep.edom.gorgeous.ReviewByUserToolboxItem":

					// Add ReviewByUser connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.ReviewByUserToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ReviewByUserToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ReviewByUserToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ReviewByUser", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ReviewByUserToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ReviewByUserFilterString)
						});
					break;
				case "isep.edom.gorgeous.ReviewHasFieldToolboxItem":

					// Add ReviewHasField connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.ReviewHasFieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ReviewHasFieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ReviewHasFieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ReviewHasField", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ReviewHasFieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ReviewHasFieldFilterString)
						});
					break;
				case "isep.edom.gorgeous.CommentByUserToolboxItem":

					// Add CommentByUser connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.CommentByUserToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CommentByUserToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CommentByUserToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CommentByUser", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CommentByUserToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(CommentByUserFilterString)
						});
					break;
				case "isep.edom.gorgeous.CommentHasFieldToolboxItem":

					// Add CommentHasField connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.CommentHasFieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						14, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CommentHasFieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CommentHasFieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CommentHasField", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CommentHasFieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(CommentHasFieldFilterString)
						});
					break;
				case "isep.edom.gorgeous.CommentHasCommentToolboxItem":

					// Add CommentHasComment connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.CommentHasCommentToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						15, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CommentHasCommentToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CommentHasCommentToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CommentHasComment", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CommentHasCommentToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(CommentHasCommentFilterString)
						});
					break;
				case "isep.edom.gorgeous.CommentExtendRevComToolboxItem":

					// Add CommentExtendRevCom connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.CommentExtendRevComToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						16, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("CommentExtendRevComToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("CommentExtendRevComToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"CommentExtendRevCom", // F1 help keyword for the toolbox item.
						resourceManager.GetString("CommentExtendRevComToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(CommentExtendRevComFilterString)
						});
					break;
				case "isep.edom.gorgeous.RevComHasFieldToolboxItem":

					// Add RevComHasField connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"isep.edom.gorgeous.RevComHasFieldToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						17, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RevComHasFieldToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RevComHasFieldToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"isep.edom.gorgeous.gorgeousToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("gorgeousToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RevComHasField", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RevComHasFieldToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RevComHasFieldFilterString)
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::isep.edom.gorgeous.gorgeousDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::isep.edom.gorgeous.gorgeousDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
