package EDOM.generator00.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.query.ReferenceTargetQuery;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_1_5(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_1_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_3_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_3_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_3_5(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(1);
  }
  public static Object propertyMacro_GetValue_3_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_3_7(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(1);
  }
  public static Object propertyMacro_GetValue_3_8(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_3_9(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_3_10(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_3_11(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_4_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_4_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_3(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_4_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_4_5(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_5_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_5_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_5_3(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_5_4(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_5_5(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object propertyMacro_GetValue_5_6(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL) + "List";
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_2(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_3(final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(1);
  }
  public static Object propertyMacro_GetValue_6_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object propertyMacro_GetValue_6_5(final PropertyMacroContext _context) {
    return "set" + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(0, 1).toUpperCase() + SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).substring(1);
  }
  public static Object propertyMacro_GetValue_6_6(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_7_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_8_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_9_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_9_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_1_0(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_1_1(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_1_2(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_1_3(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_1_4(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_1_5(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_1_6(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_1_7(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_1_8(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_0(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_3_1(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_2(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_3(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_4(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_3_5(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_3_6(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_3_7(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_8(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_3_9(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_3_10(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_3_11(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_3_12(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_3_13(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_3_14(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_3_15(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_3_16(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_3_17(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_4_0(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_4_1(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_4_2(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_4_3(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_4_4(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_4_5(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_4_6(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_4_7(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_4_8(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_5_0(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_5_1(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_5_2(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_5_3(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.commentator$exx0), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_5_4(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_5_5(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_5_6(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_5_7(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_5_8(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase() + "List";
  }
  public static Object referenceMacro_GetReferent_5_9(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_6_0(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_6_1(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_6_2(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object referenceMacro_GetReferent_6_3(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_6_4(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6_5(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Object referenceMacro_GetReferent_6_6(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6_7(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL).toLowerCase();
  }
  public static Object referenceMacro_GetReferent_6_8(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.type$$_Zl);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.subject$Pb$g);
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.subject$Pb$g);
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.subject$Pb$g);
  }
  public static Iterable<SNode> sourceNodesQuery_1_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.subject$Pb$g);
  }
  public static Iterable<SNode> sourceNodesQuery_1_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.subject$Pb$g);
  }
  public static Iterable<SNode> sourceNodesQuery_3_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attribute$ZtzL);
  }
  public static Iterable<SNode> sourceNodesQuery_3_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.user$Zu1N);
  }
  public static Iterable<SNode> sourceNodesQuery_3_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attribute$ZtzL);
  }
  public static Iterable<SNode> sourceNodesQuery_3_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.user$Zu1N);
  }
  public static Iterable<SNode> sourceNodesQuery_3_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attribute$ZtzL);
  }
  public static Iterable<SNode> sourceNodesQuery_3_5(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.user$Zu1N);
  }
  public static Iterable<SNode> sourceNodesQuery_3_6(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attribute$ZtzL);
  }
  public static Iterable<SNode> sourceNodesQuery_3_7(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.attribute$ZtzL);
  }
  public static Iterable<SNode> sourceNodesQuery_3_8(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.user$Zu1N);
  }
  public static Iterable<SNode> sourceNodesQuery_3_9(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.user$Zu1N);
  }
  public static Iterable<SNode> sourceNodesQuery_5_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.process$RRiw);
  }
  public static Iterable<SNode> sourceNodesQuery_5_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.process$RRiw);
  }
  public static Iterable<SNode> sourceNodesQuery_5_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.process$RRiw);
  }
  public static Iterable<SNode> sourceNodesQuery_5_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.process$RRiw);
  }
  public static Iterable<SNode> sourceNodesQuery_5_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.process$RRiw);
  }
  public static Iterable<SNode> sourceNodesQuery_6_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.field$zW12);
  }
  public static Iterable<SNode> sourceNodesQuery_6_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.field$zW12);
  }
  public static Iterable<SNode> sourceNodesQuery_6_2(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.field$zW12);
  }
  public static Iterable<SNode> sourceNodesQuery_6_3(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.field$zW12);
  }
  public static Iterable<SNode> sourceNodesQuery_6_4(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.field$zW12);
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("933176354013645150", new SNsQ(i++));
    snsqMethods.put("933176354014562779", new SNsQ(i++));
    snsqMethods.put("933176354014286250", new SNsQ(i++));
    snsqMethods.put("933176354014826301", new SNsQ(i++));
    snsqMethods.put("933176354014784788", new SNsQ(i++));
    snsqMethods.put("933176354017680190", new SNsQ(i++));
    snsqMethods.put("6053241114347412751", new SNsQ(i++));
    snsqMethods.put("6053241114347894551", new SNsQ(i++));
    snsqMethods.put("6053241114347912469", new SNsQ(i++));
    snsqMethods.put("6053241114347643070", new SNsQ(i++));
    snsqMethods.put("6053241114347651005", new SNsQ(i++));
    snsqMethods.put("2718252605770710603", new SNsQ(i++));
    snsqMethods.put("2718252605770793706", new SNsQ(i++));
    snsqMethods.put("2718252605771287231", new SNsQ(i++));
    snsqMethods.put("2718252605771448960", new SNsQ(i++));
    snsqMethods.put("2718252605766916999", new SNsQ(i++));
    snsqMethods.put("2718252605766960090", new SNsQ(i++));
    snsqMethods.put("2718252605766938472", new SNsQ(i++));
    snsqMethods.put("2718252605768780528", new SNsQ(i++));
    snsqMethods.put("2718252605768848093", new SNsQ(i++));
    snsqMethods.put("6053241114348246226", new SNsQ(i++));
    snsqMethods.put("6053241114348271927", new SNsQ(i++));
    snsqMethods.put("6053241114348253258", new SNsQ(i++));
    snsqMethods.put("2718252605769959989", new SNsQ(i++));
    snsqMethods.put("2718252605769993786", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_3(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_4(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_0(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_1(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_2(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_3(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_4(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_5(ctx));
        case 11:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_6(ctx));
        case 12:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_7(ctx));
        case 13:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_8(ctx));
        case 14:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_3_9(ctx));
        case 15:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_0(ctx));
        case 16:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_1(ctx));
        case 17:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_2(ctx));
        case 18:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_3(ctx));
        case 19:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_4(ctx));
        case 20:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_0(ctx));
        case 21:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_1(ctx));
        case 22:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_2(ctx));
        case 23:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_3(ctx));
        case 24:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6_4(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("933176354013773321", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "subjects"));
    pvqMethods.put("933176354014283510", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("933176354014290773", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "subjects"));
    pvqMethods.put("933176354015003560", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getSubject"));
    pvqMethods.put("933176354014798211", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "subjects"));
    pvqMethods.put("933176354014788161", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setSubject"));
    pvqMethods.put("933176354013643039", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Model"));
    pvqMethods.put("933176354017685077", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("6053241114347606800", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "users"));
    pvqMethods.put("6053241114347640608", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("6053241114347647263", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("6053241114347877134", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "users"));
    pvqMethods.put("2718252605770736940", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getField"));
    pvqMethods.put("2718252605770815673", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("2718252605770801850", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setField"));
    pvqMethods.put("2718252605771339991", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getUserList"));
    pvqMethods.put("2718252605771420313", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "users"));
    pvqMethods.put("2718252605771391172", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setUserList"));
    pvqMethods.put("933176354017677579", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Subject"));
    pvqMethods.put("2718252605766507509", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "user"));
    pvqMethods.put("2718252605766740455", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "user"));
    pvqMethods.put("2718252605768088117", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("2718252605769653586", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getUser"));
    pvqMethods.put("2718252605769707903", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "user"));
    pvqMethods.put("2718252605769692508", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setUser"));
    pvqMethods.put("2718252605766921131", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "processList"));
    pvqMethods.put("2718252605766929559", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Comment"));
    pvqMethods.put("2718252605766933949", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "user"));
    pvqMethods.put("2718252605766942586", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "processList"));
    pvqMethods.put("2718252605768800854", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getProcessList"));
    pvqMethods.put("2718252605768872986", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "processList"));
    pvqMethods.put("2718252605768854427", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setProcessList"));
    pvqMethods.put("6053241114348250498", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("6053241114348257326", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("6053241114348260368", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("2718252605769982811", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "getField"));
    pvqMethods.put("2718252605770010070", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "field"));
    pvqMethods.put("2718252605769998504", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "setField"));
    pvqMethods.put("6053241114348097779", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "User"));
    pvqMethods.put("2718252605767290480", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("2718252605767128551", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Process"));
    pvqMethods.put("2718252605767296462", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Manual"));
    pvqMethods.put("2718252605767299325", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("2718252605767301653", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Automatic"));
    pvqMethods.put("2718252605767304501", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_1_5(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_1_6(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_3_0(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetValue_3_1(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetValue_3_2(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetValue_3_3(ctx);
        case 11:
          return QueriesGenerated.propertyMacro_GetValue_3_4(ctx);
        case 12:
          return QueriesGenerated.propertyMacro_GetValue_3_5(ctx);
        case 13:
          return QueriesGenerated.propertyMacro_GetValue_3_6(ctx);
        case 14:
          return QueriesGenerated.propertyMacro_GetValue_3_7(ctx);
        case 15:
          return QueriesGenerated.propertyMacro_GetValue_3_8(ctx);
        case 16:
          return QueriesGenerated.propertyMacro_GetValue_3_9(ctx);
        case 17:
          return QueriesGenerated.propertyMacro_GetValue_3_10(ctx);
        case 18:
          return QueriesGenerated.propertyMacro_GetValue_3_11(ctx);
        case 19:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 20:
          return QueriesGenerated.propertyMacro_GetValue_4_1(ctx);
        case 21:
          return QueriesGenerated.propertyMacro_GetValue_4_2(ctx);
        case 22:
          return QueriesGenerated.propertyMacro_GetValue_4_3(ctx);
        case 23:
          return QueriesGenerated.propertyMacro_GetValue_4_4(ctx);
        case 24:
          return QueriesGenerated.propertyMacro_GetValue_4_5(ctx);
        case 25:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 26:
          return QueriesGenerated.propertyMacro_GetValue_5_1(ctx);
        case 27:
          return QueriesGenerated.propertyMacro_GetValue_5_2(ctx);
        case 28:
          return QueriesGenerated.propertyMacro_GetValue_5_3(ctx);
        case 29:
          return QueriesGenerated.propertyMacro_GetValue_5_4(ctx);
        case 30:
          return QueriesGenerated.propertyMacro_GetValue_5_5(ctx);
        case 31:
          return QueriesGenerated.propertyMacro_GetValue_5_6(ctx);
        case 32:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 33:
          return QueriesGenerated.propertyMacro_GetValue_6_1(ctx);
        case 34:
          return QueriesGenerated.propertyMacro_GetValue_6_2(ctx);
        case 35:
          return QueriesGenerated.propertyMacro_GetValue_6_3(ctx);
        case 36:
          return QueriesGenerated.propertyMacro_GetValue_6_4(ctx);
        case 37:
          return QueriesGenerated.propertyMacro_GetValue_6_5(ctx);
        case 38:
          return QueriesGenerated.propertyMacro_GetValue_6_6(ctx);
        case 39:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 40:
          return QueriesGenerated.propertyMacro_GetValue_7_1(ctx);
        case 41:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        case 42:
          return QueriesGenerated.propertyMacro_GetValue_8_1(ctx);
        case 43:
          return QueriesGenerated.propertyMacro_GetValue_9_0(ctx);
        case 44:
          return QueriesGenerated.propertyMacro_GetValue_9_1(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, ReferenceTargetQuery> rtqMethods = new HashMap<String, ReferenceTargetQuery>();
  {
    rtqMethods.put("933176354014275598", new RTQ(0, "Subject"));
    rtqMethods.put("933176354014574380", new RTQ(1, "subjects"));
    rtqMethods.put("933176354014564325", new RTQ(2, "subjects"));
    rtqMethods.put("933176354014287024", new RTQ(3, "Subject"));
    rtqMethods.put("933176354014851232", new RTQ(4, "subjects"));
    rtqMethods.put("933176354014831234", new RTQ(5, "Subject"));
    rtqMethods.put("933176354014818082", new RTQ(6, "subjects"));
    rtqMethods.put("933176354014814439", new RTQ(7, "subjects"));
    rtqMethods.put("933176354014791614", new RTQ(8, "Subject"));
    rtqMethods.put("933176354017680962", new RTQ(9, "String"));
    rtqMethods.put("6053241114347413643", new RTQ(10, "User"));
    rtqMethods.put("6053241114347900793", new RTQ(11, "field"));
    rtqMethods.put("6053241114347896008", new RTQ(12, "field"));
    rtqMethods.put("6053241114347918877", new RTQ(13, "users"));
    rtqMethods.put("6053241114347914823", new RTQ(14, "users"));
    rtqMethods.put("6053241114347643964", new RTQ(15, "String"));
    rtqMethods.put("6053241114347873948", new RTQ(16, "User"));
    rtqMethods.put("2718252605770744646", new RTQ(17, "field"));
    rtqMethods.put("2718252605770717354", new RTQ(18, "String"));
    rtqMethods.put("2718252605770829008", new RTQ(19, "field"));
    rtqMethods.put("2718252605770822486", new RTQ(20, "field"));
    rtqMethods.put("2718252605770811583", new RTQ(21, "String"));
    rtqMethods.put("2718252605771326068", new RTQ(22, "users"));
    rtqMethods.put("2718252605771293952", new RTQ(23, "User"));
    rtqMethods.put("2718252605771430438", new RTQ(24, "users"));
    rtqMethods.put("2718252605771426111", new RTQ(25, "users"));
    rtqMethods.put("2718252605771441587", new RTQ(26, "User"));
    rtqMethods.put("2718252605766502817", new RTQ(27, "User"));
    rtqMethods.put("2718252605766760281", new RTQ(28, "user"));
    rtqMethods.put("2718252605766751284", new RTQ(29, "user"));
    rtqMethods.put("2718252605766732584", new RTQ(30, "User"));
    rtqMethods.put("2718252605769665970", new RTQ(31, "user"));
    rtqMethods.put("2718252605769649678", new RTQ(32, "User"));
    rtqMethods.put("2718252605769718554", new RTQ(33, "user"));
    rtqMethods.put("2718252605769713273", new RTQ(34, "user"));
    rtqMethods.put("2718252605769701449", new RTQ(35, "User"));
    rtqMethods.put("2718252605766917896", new RTQ(36, "Process"));
    rtqMethods.put("2718252605766971345", new RTQ(37, "processList"));
    rtqMethods.put("2718252605766961968", new RTQ(38, "processList"));
    rtqMethods.put("2718252605766933940", new RTQ(39, "User"));
    rtqMethods.put("2718252605766939038", new RTQ(40, "Process"));
    rtqMethods.put("2718252605768819953", new RTQ(41, "processList"));
    rtqMethods.put("2718252605768783847", new RTQ(42, "Process"));
    rtqMethods.put("2718252605768890147", new RTQ(43, "processList"));
    rtqMethods.put("2718252605768881537", new RTQ(44, "processList"));
    rtqMethods.put("2718252605768865801", new RTQ(45, "Process"));
    rtqMethods.put("6053241114348246991", new RTQ(46, "String"));
    rtqMethods.put("6053241114348276978", new RTQ(47, "field"));
    rtqMethods.put("6053241114348273384", new RTQ(48, "field"));
    rtqMethods.put("6053241114348254146", new RTQ(49, "String"));
    rtqMethods.put("2718252605769988793", new RTQ(50, "field"));
    rtqMethods.put("2718252605769963671", new RTQ(51, "String"));
    rtqMethods.put("2718252605770020891", new RTQ(52, "field"));
    rtqMethods.put("2718252605770013562", new RTQ(53, "field"));
    rtqMethods.put("2718252605770004849", new RTQ(54, "String"));
  }
  @NotNull
  @Override
  public ReferenceTargetQuery getReferenceTargetQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(rtqMethods.containsKey(id))) {
      return super.getReferenceTargetQuery(queryKey);
    }
    return rtqMethods.get(id);
  }
  private static class RTQ extends ReferenceTargetQuery.Base {
    private final int methodKey;
    /*package*/ RTQ(int methodKey, String templateValue) {
      super(templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull ReferenceMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.referenceMacro_GetReferent_1_0(ctx);
        case 1:
          return QueriesGenerated.referenceMacro_GetReferent_1_1(ctx);
        case 2:
          return QueriesGenerated.referenceMacro_GetReferent_1_2(ctx);
        case 3:
          return QueriesGenerated.referenceMacro_GetReferent_1_3(ctx);
        case 4:
          return QueriesGenerated.referenceMacro_GetReferent_1_4(ctx);
        case 5:
          return QueriesGenerated.referenceMacro_GetReferent_1_5(ctx);
        case 6:
          return QueriesGenerated.referenceMacro_GetReferent_1_6(ctx);
        case 7:
          return QueriesGenerated.referenceMacro_GetReferent_1_7(ctx);
        case 8:
          return QueriesGenerated.referenceMacro_GetReferent_1_8(ctx);
        case 9:
          return QueriesGenerated.referenceMacro_GetReferent_3_0(ctx);
        case 10:
          return QueriesGenerated.referenceMacro_GetReferent_3_1(ctx);
        case 11:
          return QueriesGenerated.referenceMacro_GetReferent_3_2(ctx);
        case 12:
          return QueriesGenerated.referenceMacro_GetReferent_3_3(ctx);
        case 13:
          return QueriesGenerated.referenceMacro_GetReferent_3_4(ctx);
        case 14:
          return QueriesGenerated.referenceMacro_GetReferent_3_5(ctx);
        case 15:
          return QueriesGenerated.referenceMacro_GetReferent_3_6(ctx);
        case 16:
          return QueriesGenerated.referenceMacro_GetReferent_3_7(ctx);
        case 17:
          return QueriesGenerated.referenceMacro_GetReferent_3_8(ctx);
        case 18:
          return QueriesGenerated.referenceMacro_GetReferent_3_9(ctx);
        case 19:
          return QueriesGenerated.referenceMacro_GetReferent_3_10(ctx);
        case 20:
          return QueriesGenerated.referenceMacro_GetReferent_3_11(ctx);
        case 21:
          return QueriesGenerated.referenceMacro_GetReferent_3_12(ctx);
        case 22:
          return QueriesGenerated.referenceMacro_GetReferent_3_13(ctx);
        case 23:
          return QueriesGenerated.referenceMacro_GetReferent_3_14(ctx);
        case 24:
          return QueriesGenerated.referenceMacro_GetReferent_3_15(ctx);
        case 25:
          return QueriesGenerated.referenceMacro_GetReferent_3_16(ctx);
        case 26:
          return QueriesGenerated.referenceMacro_GetReferent_3_17(ctx);
        case 27:
          return QueriesGenerated.referenceMacro_GetReferent_4_0(ctx);
        case 28:
          return QueriesGenerated.referenceMacro_GetReferent_4_1(ctx);
        case 29:
          return QueriesGenerated.referenceMacro_GetReferent_4_2(ctx);
        case 30:
          return QueriesGenerated.referenceMacro_GetReferent_4_3(ctx);
        case 31:
          return QueriesGenerated.referenceMacro_GetReferent_4_4(ctx);
        case 32:
          return QueriesGenerated.referenceMacro_GetReferent_4_5(ctx);
        case 33:
          return QueriesGenerated.referenceMacro_GetReferent_4_6(ctx);
        case 34:
          return QueriesGenerated.referenceMacro_GetReferent_4_7(ctx);
        case 35:
          return QueriesGenerated.referenceMacro_GetReferent_4_8(ctx);
        case 36:
          return QueriesGenerated.referenceMacro_GetReferent_5_0(ctx);
        case 37:
          return QueriesGenerated.referenceMacro_GetReferent_5_1(ctx);
        case 38:
          return QueriesGenerated.referenceMacro_GetReferent_5_2(ctx);
        case 39:
          return QueriesGenerated.referenceMacro_GetReferent_5_3(ctx);
        case 40:
          return QueriesGenerated.referenceMacro_GetReferent_5_4(ctx);
        case 41:
          return QueriesGenerated.referenceMacro_GetReferent_5_5(ctx);
        case 42:
          return QueriesGenerated.referenceMacro_GetReferent_5_6(ctx);
        case 43:
          return QueriesGenerated.referenceMacro_GetReferent_5_7(ctx);
        case 44:
          return QueriesGenerated.referenceMacro_GetReferent_5_8(ctx);
        case 45:
          return QueriesGenerated.referenceMacro_GetReferent_5_9(ctx);
        case 46:
          return QueriesGenerated.referenceMacro_GetReferent_6_0(ctx);
        case 47:
          return QueriesGenerated.referenceMacro_GetReferent_6_1(ctx);
        case 48:
          return QueriesGenerated.referenceMacro_GetReferent_6_2(ctx);
        case 49:
          return QueriesGenerated.referenceMacro_GetReferent_6_3(ctx);
        case 50:
          return QueriesGenerated.referenceMacro_GetReferent_6_4(ctx);
        case 51:
          return QueriesGenerated.referenceMacro_GetReferent_6_5(ctx);
        case 52:
          return QueriesGenerated.referenceMacro_GetReferent_6_6(ctx);
        case 53:
          return QueriesGenerated.referenceMacro_GetReferent_6_7(ctx);
        case 54:
          return QueriesGenerated.referenceMacro_GetReferent_6_8(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty type$$_Zl = MetaAdapterFactory.getProperty(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe61952dafL, 0x214447fe61952db2L, "type");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink commentator$exx0 = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe61954b3aL, 0x214447fe61954b3dL, "commentator");
    /*package*/ static final SContainmentLink subject$Pb$g = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe6193d5b9L, 0x214447fe6194630aL, "subject");
    /*package*/ static final SContainmentLink attribute$ZtzL = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe61929cbbL, 0x214447fe61952db8L, "attribute");
    /*package*/ static final SContainmentLink user$Zu1N = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe61929cbbL, 0x214447fe61952dbaL, "user");
    /*package*/ static final SContainmentLink process$RRiw = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x4dd8eed996c07227L, 0x2c8dc50d8beafd09L, "process");
    /*package*/ static final SContainmentLink field$zW12 = MetaAdapterFactory.getContainmentLink(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x214447fe61929cdbL, 0xcf34ef325b79323L, "field");
  }
}
