package EDOM.sandbox;

/*Generated by MPS */


public class Commentator {

  private String name;
  private String gender;
  private String reputation;

  public Commentator(String name, String gender, String reputation) {
    this.name = name;
    this.gender = gender;
    this.reputation = reputation;
  }
}
