package EDOM.sandbox;

/*Generated by MPS */

import java.util.List;

public class Process1 {

  private List<Node> nodeList;

  public Process1(List<Node> nodeList) {
    this.nodeList = nodeList;
  }
}
