package EDOM.sandbox;

/*Generated by MPS */


public class Publisher {

  private String name;
  private String gender;
  private String reputation;
  private Integer peso;

  public Publisher(String name, String gender, String reputation, Integer peso) {
    this.name = name;
    this.gender = gender;
    this.reputation = reputation;
    this.peso = peso;
  }
}
