package EDOM.sandbox;

/*Generated by MPS */


public abstract class ReviewComment {

  private String comentario;
  private Commentator commentator;

  public ReviewComment(String comentario, Commentator commentator) {
    this.comentario = comentario;
    this.commentator = commentator;
  }
}
