package EDOM.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class setValidation_QuickFix extends QuickFix_Runtime {
  public setValidation_QuickFix() {
    super(new SNodePointer("r:24cc4b2d-8303-4892-a788-3e484b8e8944(EDOM.typesystem)", "5698975515764237660"));
  }
  public String getDescription(SNode node) {
    return "Set validation to approved";
  }
  public void execute(SNode node) {
    SPropertyOperations.assign(SNodeOperations.as(node, CONCEPTS.Node$nY), PROPS.isAccepted$AH2N, "APPROVED");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Node$nY = MetaAdapterFactory.getConcept(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x2c8dc50d8beafcfeL, "EDOM.structure.Node");
  }

  private static final class PROPS {
    /*package*/ static final SProperty isAccepted$AH2N = MetaAdapterFactory.getProperty(0x93a85216feee47faL, 0xa39e2320d26e7cceL, 0x2c8dc50d8beafcfeL, 0x4f16d40980baa2dbL, "isAccepted");
  }
}
